language: r
cache: packages
dist: trusty
sudo: required

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev
  - Rscript -e 'update.packages(ask = FALSE)'

notifications:
  email:
    on_success: change
    on_failure: change

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=false

r_github_packages:
    - bcgov/bcmaps.rdata
r:
  - release
  - devel
